### ISSUE TITLE
Horizontal slider on home page

### ISSUE THREAD

**Issue by violabazanye** [violabazanye/Yocktail#2]
Trying to implement horizontal slider on home page for popular cocktails because I can't  limit the number of results returned so best options to use horizontal slider to display the results but having some difficulty, any thoughts...??

**Comment by violabazanye** [comment]
figured out how to limit number of results, but if you know how to implement the horizontal slider please feel free to do so, I can edit the api to accommodate it.

**Comment by yangzhihao519** [comment]
http://www.bootply.com/l2ChB4vYmC
http://stackoverflow.com/questions/19800008/create-horizontally-scrolling-list-item-view-using-bootstrap-columns
These might be useful

we could leave this as a feature to implement after we have finished all the main functions.
